### ISSUE TITLE
Multiple refreshTokens

### ISSUE THREAD

**Issue by Eimis** [flavors/django-graphql-jwt#109]
Hello,

I have a couple of questions. I am using Long running refresh tokens, but I don't fully understand a few concepts and implementations in this library.

1)
```
mutation RefreshToken($refreshToken: String!) {
  refreshToken(refreshToken: $refreshToken) {
    token
    refreshToken
    payload
  }
}
```
In the docs it says "refreshToken to refresh your _token_, using the refreshToken you already got during authorization:". But why is it creating a new `refreshToken` every time and saving it in my database? I understand that I am asking for a `refreshToken` in return with this query every time (it's not creating a new one if I'm not asking for a `refreshToken` in my query, thanks for #72 !), but why is it generating a new `refreshToken` every time ?

2) 
```
mutation TokenAuth($email: String!, $password: String!) {
  tokenAuth(email: $email, password: $password) {
    token
    refreshToken
  }
}
```

A very similar question. If I'm not asking for a `refreshToken`, it's not creating a new one, but if I do, it's creating a new `refreshToken` every time I'm authenticating, thus potentially leading to  polluting the database with multiple refreshTokens for a single user, which creates a mess and doesn't make much sense.

1) What could be possible solutions of having only 1 `refreshToken` per user in my database ?
2) I assume since I am asking for `refreshToken` every time in the query, this is the desired functionality of the library and it is my responsibility to make sure old one is removed when new one is issued ?

**Comment by Dawidpol** [comment]
I am actually also interested if it is just a bug or there is a reasoning behind it. I can think of one: Like maybe you have one user logged on few diffrent devices, so you do not want to log him out suddenly from other devices, when someones refreshed Refresh token on some device.

**Comment by douglasspeights** [comment]
From what I've done (and it seems to work effectively) is the following (concept based on [One Time Use refreshTokens](https://django-graphql-jwt.domake.io/en/latest/refresh_token.html#one-time-only-use-refresh-token):

1. Use username:password to gain `token` _and_ `refreshToken`
2. Use `token` in all authentication-required requests (for the next Xm(default 5m))
3. On request where `token` is _expired_, send `refreshToken` to the **graphql_jwt.Refresh.Field()**, requesting a new `token` _and_ `refreshToken`, update and resend request

What this provides:
1.  Use `refreshToken`, instead of `username:password`, to gain a new `token` every ** JWT_EXPIRATION_DELTA**
2.  Single-use `refreshToken` is database-stored, recording its life/usage, but only valid for ** JWT_REFRESH_EXPIRATION_DELTA** days (default 7)
3.  Allows for end-user to not be required a new `username:password` login for at least 7 days from their `refreshToken` creation, yet still forcing short-lived JWTs

I, also, wouldn't mind more clarity on the ideal/designed `refreshToken` use cases, but, rather than manually trying to revoke tokens or clean refreshTokens, using Single-Use seems like a good alternative.
It wouldn't be hard to extend the `refresh_token` Field so you can include checks for existing, valid, refreshTokens, and then clean them up, since a new one was requested.  Here's an example of how I extended it to inject logging:

```
class RefreshToken(graphql_jwt.relay.Refresh):
    class Meta:
        description = """Generate a new refreshToken (via token)"""

    class Input(graphql_jwt.relay.mixins.RefreshMixin.Fields):
        refresh_token = graphene.String(required=True, description="refreshToken to use")

    @classmethod
    def mutate_and_get_payload(cls, *args, **kwargs):
        # Add your custom checks/logic here ...
        return cls.refresh(*args, **kwargs)
```

**Comment by ryarasi** [comment]
If anyone stumbles upon this, I found a way to configure the reuse of refreshtokens so that new records are not created every time refreshtoken is requested.

```
GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    'JWT_REUSE_REFRESH_TOKENS': True, # Eliminates creation of new db records every time refreshtoken is requested.
    'JWT_EXPIRATION_DELTA': timedelta(minutes=60), # Expiry time of token
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7), # Expiry time of refreshToken
}
```

[Source](https://readthedocs.org/projects/django-graphql-jwt/downloads/pdf/latest/)
