### ISSUE TITLE
Override configuration settings with arguments

### ISSUE THREAD

**Issue by maarcingebala** [flavors/django-graphql-jwt#12]
Currently, all the configuration is taken from environment variables, but I'd like to be able to override those values with custom settings dynamically. The reason for that is that I need to serve two different APIs from the same server: 
- public API exposing a limited set of data meant to be used by a public client application,
- private API, protected with password and permission mechanisms meant to be used by an internal administration app.

In this scenario, I'd like to use two different `JWT_AUDIENCE` values for each API so that the tokens from the first one cannot be used in the second. I could achieve that by customizing `JSONWebTokenMutation`, `token_auth` decorator and passing extra data to `get_token` to override values from env in the payload.

@mongkok What are your thoughts on this? Would you be interested in including such feature in the library? If yes, I could work on a proof-of-concept PR.

**Comment by mongkok** [comment]
Hi @elwoodxblues,
are the API's included in the same Django-project?

You could use the `is_staff` field and *user permissions* to protect resolvers and mutations from private API.

**Comment by elwoodxblues** [comment]
Yes, that's the case - they are in the same Django project since they share the database and most of the business logic, but it's easier for us to have two `/graphql/` endpoints to manage access to public and private data. We already use `is_staff` to make sure that only staff has access to nodes exposed in the private API. Also, the permission system will be used as the staff users can have different permissions in our system. 
We wanted to use the `JWT_AUDIENCE` to take full advantage of what JWT offers and make sure that the tokens from both APIs cannot be mixed.

**Comment by mongkok** [comment]
I think your propose is interesting,
which is the approach you are considering?

**Comment by elwoodxblues** [comment]
Don't know yet exactly, I only looked at the source code for a while, but I would try with passing custom settings to mutation fields directly, e.g.:
```
graphql_jwt.ObtainJSONWebToken.Field(JWT_AUDIENCE='public')
```
I would pass it down to where the payload is constructed and env variables are read. That's just the rough idea, but I think it might work. I'll try to work on it when I have time and if I come up with a reasonable solution I'll open a PR.

**Comment by mongkok** [comment]
Currently, `Mutation.Field()` doesn't propagate custom arguments.

From my point of view, we could give the possibility to customize the functions `jwt_payload`, `jwt_encode` and `jwt_decode`, it is a simpler solution and allows you to develop more use cases (same as [django-rest-framework-jwt](https://getblimp.github.io/django-rest-framework-jwt/#additional-settings)).

**Comment by elwoodxblues** [comment]
This could be handy in some cases but I think it won't solve my problem. Even if I override `jwt_payload` with my own function, it would be used by both APIs anyway and I won't be able to dynamically determine what `JWT_AUDIENCE` value should be used.

**Comment by mongkok** [comment]
Passing the settings as argument in a mutation is a good idea, but in this case I think it could be confusing because the settings variables are required in different ways.

- `JWT_AUDIENCE` is required for all mutations
- `JWT_VERIFY` or `JWT_LEEWAY` are required for `Verify` and `Refresh` but not for `ObtainJSONWebToken`
- `JWT_AUTH_HEADER_PREFIX` is not used in mutations.

If we use a unique setting with a variable `JWT_PAYLOAD_HANDLER` passing the `context` variable, you could configure the `aud` key dynamically using `context.build_absolute_uri()` or `context.path_info`.

```py
from graphql_jwt.utils import jwt_payload


def jwt_payload_handler(user, context):
    payload = jwt_payload(user)
    payload['aud'] = context.build_absolute_uri()
    return payload
```
