### ISSUE TITLE
Django 3.0 incompatibility

### ISSUE THREAD

**Issue by lassesteffen** [flavors/django-graphql-jwt#150]
Django just released version 3 of their framework https://docs.djangoproject.com/en/3.0/releases/3.0/

One change is : 
> django.utils.six - Remove usage of this vendored library or switch to six.
> django.utils.encoding.python_2_unicode_compatible() - Alias of six.python_2_unicode_compatible().

This breaks this library because it does import six in some places.

Is there anything I can do to get this fixed?

**Comment by lassesteffen** [comment]
IMO this library should drop python 2 support as django does

**Comment by valberg** [comment]
Can we do anything to move this along?

**Comment by coltonbh** [comment]
For those of us building from the maser branch and using Django<3.0 this creates an additional problem. The problem lies in the `setup.py` file where the install_requires `'Django>=1.11'`. This should be changed to `'Django<=2.2'` since the package is not compatible with Django 3.0 yet. For those of us building from the master branch (to get a few recent bug fixes) this breaks our build ability to build since pipenv prioritiezes non-pypi package dependency resolution. So even though I specify Django==2.2 in my Pipfile, I'll get Django 3.0 if I build using the master branch of this repo.

**Comment by BfutureP** [comment]
doesn't support django 3.0 please propvide support

**Comment by mongkok** [comment]
Thanks for the PRs :)
I have created [2 new releases](https://github.com/flavors/django-graphql-jwt/releases):
- 0.2.3: last release that supports python 2.7
- 0.3.0: first release that supports Django3

If you have any questions please let me know.

**Comment by valberg** [comment]
Awesome! Thanks @mongkok for an awesome library! :tada:

**Comment by coltonbh** [comment]
Happy to contribute! Even if it was just one line 😂
