### ISSUE TITLE
JWT_COOKIE_SAMESITE = 'None' not being respected

### ISSUE THREAD

**Issue by JavierPiedra** [flavors/django-graphql-jwt#216]
Hi! I have installed version 0.3.1 as my pipenv update --outdated show:
django-graphql-jwt: 0.3.1 installed, 0.3.1 required (Unpinned in Pipfile), 0.3.1 available.

And recently with the new change on Chrome policy regarding the cookies I saw that we needed to secure cookies when setting samesite none. More [here](https://www.chromestatus.com/feature/5633521622188032)

However, although I explicitly set this setting accordingly:
```
GRAPHQL_JWT = {
    'JWT_ALLOW_ARGUMENT': False,
    'JWT_HIDE_TOKEN_FIELDS': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=15),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7),
    'JWT_COOKIE_SECURE': config('JWT_COOKIE_SECURE', cast=bool, default=True),
    'JWT_COOKIE_SAMESITE': 'None',
    'JWT_CSRF_ROTATION': True,
}
```
The cookie is being delivered secure but the SAMESITE property is delivered as Lax. 
I saw the PR #214, actually I had the latest version by that moment and I reinstall, check everything becuase of this new policy, and while Django settings regarding CSRF are working (on chrome I'm receiveng correct props), this one doesn't

My Django settings that are working:
```
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = config(
    'CSRF_COOKIE_SECURE', default=True, cast=bool)
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = config(
    'SESSION_COOKIE_SECURE', default=True, cast=bool)
```

**Comment by deanpienaar** [comment]
👍  Yeah. Would really appreciate this fix being released.

**Comment by JavierPiedra** [comment]
@mongkok  Also, I realized when I installed directly form github master, that there are version conflicts as graphene-django and django-graphql-jwt rely on different versions of graphene. This happen when you have graphene on the requirements.txt or Pipfile. I'd love to create my first contribution on a public package but I'm not sure how to do that accordingly :(

**Comment by castin1010** [comment]
This version is still not available on PyPi, any advice on how I can work around this for now?

**Comment by JavierPiedra** [comment]
> This version is still not available on PyPi, any advice on how I can work around this for now?

pipenv install git+https://github.com/flavors/django-graphql-jwt#egg=django-graphql-jwt

**Comment by fbennets** [comment]
It's really confusing, that this feature is already part of the documentation but not implemented. @mongkok should I make a PR with a comment in the documentation? I guess that would be really helpful.

> This version is still not available on PyPi, any advice on how I can work around this for now?

With pip you can install directly from a git repo. Just remove the entry for django-graphql-jwt from you requirements.txt and add the last line in the example below.

```
Django==3.0.7
django-allauth==0.41.0
git+git://github.com/flavors/django-graphql-jwt@master#egg=django-graphql-jwt
```

However, this will always get the most recent version from master - you don't have a fixed version. You could also install from a commit using its hash instead of using "master". At the current state of the repo contains breaking changes. Therefore I forked the repo, rolled back to the code used for version 0.31 and just added the two lines (see [here](https://github.com/open-decision/django-graphql-jwt/commit/db413d58cfdbb90cd37f8950808c03558633415e)).

Then you can get version 0.31 including the JWT_COOKIE_SAMESITE.

Feel free to use my modified version (just paste this into your requriements):
`git+git://github.com/open-decision/django-graphql-jwt@mod#egg=django-graphql-jwt`

But better fork it on your own, if I'll make changes in the future.

**Comment by mongkok** [comment]
I'm sorry guys, I added it to the docs before creating a new release.
Thanks @fbennets for the help here!

**Comment by gsi-chao** [comment]
Any progress with this request?
