### ISSUE TITLE
Expired token does not throw 401 NOT ALLOWED

### ISSUE THREAD

**Issue by premma** [flavors/django-graphql-jwt#265]
And what is even worse:
```

class PermissionDenied(JSONWebTokenError):
    default_message = _('You do not have permission to perform this action')


class JSONWebTokenExpired(JSONWebTokenError):
    default_message = _('Signature has expired')

```
errors that it returns are TRANSLATED into different languages. So it will throw different error message!!! Oh my god, this is so big fail. Is anybody there, that maintains this code? and if so, could it return some more specific code and not just a translated string?

**Comment by mongkok** [comment]
It's common/good practice to use HTTP 200 for all GraphQL responses, GraphQL doesn't care about the transport layer.
On the other hand consider that GraphQL supports multiple operations in a single request, some operations may have an authentication error and others may not.

As for error handling, you can customize the error format and include the `extensions` key ([see spec](https://spec.graphql.org/June2018/#sec-Errors)), I don't think using the message field is the best approach.

I close the issue because I don't think this behaviour should change, if you have any comments please let me know.

**Comment by premma** [comment]
Wait a minute, the error is thrown from inside of the code and cannot be changed, unless I rewrite the method `get_payload`, where the errors are raised. 

Why haven't you included the `extension` key with a code from the beginning? This implementation (simple message that can change according to user's language) is the worst possible solution that was chosen.. And even though the whole code is pretty customizable, the errors and the mechanism of checking the payload is deep and frozen in the code. 

I disagree with closing the issue and suggest you could alter the code (adding the to code to determine that the token is expired) Is that possible?
