### ISSUE TITLE
Refresh token as cookie

### ISSUE THREAD

**Issue by nchouard** [flavors/django-graphql-jwt#95]
The jwt_cookie feature has proven to be extremely helpful and has fixed some of my security concerns related to storing the tokens in the browser. However, because only the access token is sent as a cookie, I would still have to use local or session storage to store the refresh token if I want to use them. Doesn't this kind of defeat the purpose of having a JWT cookie? Would it be possible to send a refresh token as a cookie as well?

Thank you for all of your work.

**Comment by mongkok** [comment]
Thanks @nchouard,
I'm sorry for the delay in my response.

Fully agree, if you set `JWT_LONG_RUNNING_REFRESH_TOKEN` to `True`, the refresh token should be able to be sent as a cookie., I will start working on this soon.

**Comment by charl3sj** [comment]
@nchouard @mongkok  Would be great if you could help me understand this... how does one access and use this refresh token cookie if the refresh token has to be sent as a argument to the refreshToken mutation?

**Comment by mcabrams** [comment]
@charl3sj @nchouard According to documentation it should be getting set in the response if it is passed in query to auth token.  I'm not seeing that myself -- not sure if this is due to misconfiguration on my end, however, looking at the code I did a search for `jwt_refresh_token` and found the following two instances:
https://github.com/flavors/django-graphql-jwt/blob/558b72302e34ba1c707c47a886d95e8ea4a468e4/graphql_jwt/decorators.py#L135

https://github.com/flavors/django-graphql-jwt/blob/fd5a4cd010816cfed0c8730584e634953b0902df/graphql_jwt/refresh_token/mixins.py#L34

The significant line to me was the former in `decorators.py`.  It seems to me like that would never evaluate to true as things stand?  I may be missing some other place where `request.jwt_refresh_token` would get set to true.  Any insight on this @mongkok ?

**Comment by Jawmo** [comment]
Did this ever get resolved? I am seeing the same issue. The mutation wants a token input but if you can't get the httpOnly refresh token from the client, how does it get sent over to the server?

I assume you are supposed to just call it, without variables, and the server pulls the cookie to use and returns a new authToken.

But why does this not happen if I remove the variables from the mutation? What has to be set for this to happen?

I already have the following set: 
...
from graphql_jwt.decorators import jwt_cookie
...
path('graphql/', jwt_cookie(csrf_exempt(GraphQLView.as_view(graphiql=True)))),
...
